/*
==================================================================
ARCHIVO: formulario/sidebar/_config.js
Configuración y datos estáticos del sidebar form
==================================================================
*/

export const SIDEBAR_STORAGE_KEY = 'sidebarFormProgress';

// Endpoint del Cloudflare Worker (placeholder hasta despliegue)
export const WORKER_URL = 'https://form.planespro.cl/submit';

export const RANGOS_RENTA = [
    'Menos de $500.000',
    '$500.000 - $800.000',
    '$800.001 - $1.200.000',
    '$1.200.001 - $2.000.000',
    'Más de $2.000.000',
];

export const ISAPRES = [
    'Banmédica',
    'Colmena',
    'Cruz Blanca',
    'Esencial',
    'Nueva Masvida',
    'Vida Tres',
    'Otra',
];

export const comunasRegiones = {
    "Arica": "Arica y Parinacota", "Camarones": "Arica y Parinacota", "Putre": "Arica y Parinacota", "General Lagos": "Arica y Parinacota", "Iquique": "Tarapacá", "Alto Hospicio": "Tarapacá", "Pozo Almonte": "Tarapacá", "Camiña": "Tarapacá", "Colchane": "Tarapacá", "Huara": "Tarapacá", "Pica": "Tarapacá", "Antofagasta": "Antofagasta", "Mejillones": "Antofagasta", "Sierra Gorda": "Antofagasta", "Taltal": "Antofagasta", "Calama": "Antofagasta", "Ollagüe": "Antofagasta", "San Pedro de Atacama": "Antofagasta", "Tocopilla": "Antofagasta", "María Elena": "Antofagasta", "Copiapó": "Atacama", "Caldera": "Atacama", "Tierra Amarilla": "Atacama", "Chañaral": "Atacama", "Diego de Almagro": "Atacama", "Vallenar": "Atacama", "Alto del Carmen": "Atacama", "Freirina": "Atacama", "Huasco": "Atacama", "La Serena": "Coquimbo", "Coquimbo": "Coquimbo", "Andacollo": "Coquimbo", "La Higuera": "Coquimbo", "Paiguano": "Coquimbo", "Vicuña": "Coquimbo", "Illapel": "Coquimbo", "Canela": "Coquimbo", "Los Vilos": "Coquimbo", "Salamanca": "Coquimbo", "Ovalle": "Coquimbo", "Combarbalá": "Coquimbo", "Monte Patria": "Coquimbo", "Punitaqui": "Coquimbo", "Río Hurtado": "Coquimbo", "Valparaíso": "Valparaíso", "Casablanca": "Valparaíso", "Concón": "Valparaíso", "Juan Fernández": "Valparaíso", "Puchuncaví": "Valparaíso", "Quintero": "Valparaíso", "Viña del Mar": "Valparaíso", "Isla de Pascua": "Valparaíso", "Los Andes": "Valparaíso", "Calle Larga": "Valparaíso", "Rinconada": "Valparaíso", "San Esteban": "Valparaíso", "La Ligua": "Valparaíso", "Cabildo": "Valparaíso", "Papudo": "Valparaíso", "Petorca": "Valparaíso", "Zapallar": "Valparaíso", "Quillota": "Valparaíso", "Calera": "Valparaíso", "Hijuelas": "Valparaíso", "La Cruz": "Valparaíso", "Nogales": "Valparaíso", "San Antonio": "Valparaíso", "Algarrobo": "Valparaíso", "Cartagena": "Valparaíso", "El Quisco": "Valparaíso", "El Tabo": "Valparaíso", "Santo Domingo": "Valparaíso", "San Felipe": "Valparaíso", "Catemu": "Valparaíso", "Llaillay": "Valparaíso", "Panquehue": "Valparaíso", "Putaendo": "Valparaíso", "Santa María": "Valparaíso", "Limache": "Valparaíso", "Quilpué": "Valparaíso", "Villa Alemana": "Valparaíso", "Olmué": "Valparaíso",
    "Rancagua": "O'Higgins", "Codegua": "O'Higgins", "Coinco": "O'Higgins", "Coltauco": "O'Higgins", "Doñihue": "O'Higgins", "Graneros": "O'Higgins", "Las Cabras": "O'Higgins", "Machalí": "O'Higgins", "Malloa": "O'Higgins", "Mostazal": "O'Higgins", "Olivar": "O'Higgins", "Peumo": "O'Higgins", "Pichidegua": "O'Higgins", "Quinta de Tilcoco": "O'Higgins", "Rengo": "O'Higgins", "Requínoa": "O'Higgins", "San Vicente": "O'Higgins", "Pichilemu": "O'Higgins", "La Estrella": "O'Higgins", "Litueche": "O'Higgins", "Marchihue": "O'Higgins", "Navidad": "O'Higgins", "Paredones": "O'Higgins", "San Fernando": "O'Higgins", "Chépica": "O'Higgins", "Chimbarongo": "O'Higgins", "Lolol": "O'Higgins", "Nancagua": "O'Higgins", "Palmilla": "O'Higgins", "Peralillo": "O'Higgins", "Placilla": "O'Higgins", "Pumanque": "O'Higgins", "Santa Cruz": "O'Higgins",
    "Talca": "Maule", "Constitución": "Maule", "Curepto": "Maule", "Empedrado": "Maule", "Maule": "Maule", "Pelarco": "Maule", "Pencahue": "Maule", "Río Claro": "Maule", "San Clemente": "Maule", "San Rafael": "Maule", "Cauquenes": "Maule", "Chanco": "Maule", "Pelluhue": "Maule", "Curicó": "Maule", "Hualañé": "Maule", "Licantén": "Maule", "Molina": "Maule", "Rauco": "Maule", "Romeral": "Maule", "Sagrada Familia": "Maule", "Teno": "Maule", "Vichuquén": "Maule", "Linares": "Maule", "Colbún": "Maule", "Longaví": "Maule", "Parral": "Maule", "Retiro": "Maule", "San Javier": "Maule", "Villa Alegre": "Maule", "Yerbas Buenas": "Maule",
    "Concepción": "Biobío", "Coronel": "Biobío", "Chiguayante": "Biobío", "Florida": "Biobío", "Hualqui": "Biobío", "Lota": "Biobío", "Penco": "Biobío", "San Pedro de la Paz": "Biobío", "Santa Juana": "Biobío", "Talcahuano": "Biobío", "Tomé": "Biobío", "Hualpén": "Biobío", "Lebu": "Biobío", "Arauco": "Biobío", "Cañete": "Biobío", "Contulmo": "Biobío", "Curanilahue": "Biobío", "Los Alamos": "Biobío", "Tirúa": "Biobío", "Los Angeles": "Biobío", "Antuco": "Biobío", "Cabrero": "Biobío", "Laja": "Biobío", "Mulchén": "Biobío", "Nacimiento": "Biobío", "Negrete": "Biobío", "Quilaco": "Biobío", "Quilleco": "Biobío", "San Rosendo": "Biobío", "Santa Bárbara": "Biobío", "Tucapel": "Biobío", "Yumbel": "Biobío", "Alto Biobío": "Biobío",
    "Chillán": "Ñuble", "Bulnes": "Ñuble", "Cobquecura": "Ñuble", "Coelemu": "Ñuble", "Coihueco": "Ñuble", "Chillán Viejo": "Ñuble", "El Carmen": "Ñuble", "Ninhue": "Ñuble", "Niquén": "Ñuble", "Pemuco": "Ñuble", "Pinto": "Ñuble", "Portezuelo": "Ñuble", "Quillón": "Ñuble", "Quirihue": "Ñuble", "Ránquil": "Ñuble", "San Carlos": "Ñuble", "San Fabián": "Ñuble", "San Ignacio": "Ñuble", "San Nicolás": "Ñuble", "Treguaco": "Ñuble", "Yungay": "Ñuble",
    "Temuco": "La Araucanía", "Carahue": "La Araucanía", "Cunco": "La Araucanía", "Curarrehue": "La Araucanía", "Freire": "La Araucanía", "Galvarino": "La Araucanía", "Gorbea": "La Araucanía", "Lautaro": "La Araucanía", "Loncoche": "La Araucanía", "Melipeuco": "La Araucanía", "Nueva Imperial": "La Araucanía", "Padre Las Casas": "La Araucanía", "Perquenco": "La Araucanía", "Pitrufquén": "La Araucanía", "Pucón": "La Araucanía", "Saavedra": "La Araucanía", "Teodoro Schmidt": "La Araucanía", "Toltén": "La Araucanía", "Vilcún": "La Araucanía", "Villarrica": "La Araucanía", "Cholchol": "La Araucanía", "Angol": "La Araucanía", "Collipulli": "La Araucanía", "Curacautín": "La Araucanía", "Ercilla": "La Araucanía", "Lonquimay": "La Araucanía", "Los Sauces": "La Araucanía", "Lumaco": "La Araucanía", "Purén": "La Araucanía", "Renaico": "La Araucanía", "Traiguén": "La Araucanía", "Victoria": "La Araucanía",
    "Valdivia": "Los Ríos", "Corral": "Los Ríos", "Lanco": "Los Ríos", "Los Lagos": "Los Ríos", "Máfil": "Los Ríos", "Mariquina": "Los Ríos", "Paillaco": "Los Ríos", "Panguipulli": "Los Ríos", "La Unión": "Los Ríos", "Futrono": "Los Ríos", "Lago Ranco": "Los Ríos", "Río Bueno": "Los Ríos",
    "Puerto Montt": "Los Lagos", "Calbuco": "Los Lagos", "Cochamó": "Los Lagos", "Fresia": "Los Lagos", "Frutillar": "Los Lagos", "Los Muermos": "Los Lagos", "Llanquihue": "Los Lagos", "Maullín": "Los Lagos", "Puerto Varas": "Los Lagos", "Castro": "Los Lagos", "Ancud": "Los Lagos", "Chonchi": "Los Lagos", "Curaco de Vélez": "Los Lagos", "Dalcahue": "Los Lagos", "Puqueldón": "Los Lagos", "Queilén": "Los Lagos", "Quellón": "Los Lagos", "Quemchi": "Los Lagos", "Quinchao": "Los Lagos", "Osorno": "Los Lagos", "Puerto Octay": "Los Lagos", "Purranque": "Los Lagos", "Puyehue": "Los Lagos", "Río Negro": "Los Lagos", "San Juan de la Costa": "Los Lagos", "San Pablo": "Los Lagos", "Chaitén": "Los Lagos", "Futaleufú": "Los Lagos", "Hualaihué": "Los Lagos", "Palena": "Los Lagos",
    "Coihaique": "Aysén", "Lago Verde": "Aysén", "Aisén": "Aysén", "Cisnes": "Aysén", "Guaitecas": "Aysén", "Cochrane": "Aysén", "O'Higgins": "Aysén", "Tortel": "Aysén", "Chile Chico": "Aysén", "Río Ibáñez": "Aysén",
    "Punta Arenas": "Magallanes", "Laguna Blanca": "Magallanes", "Río Verde": "Magallanes", "San Gregorio": "Magallanes", "Cabo de Hornos": "Magallanes", "Antártica": "Magallanes", "Porvenir": "Magallanes", "Primavera": "Magallanes", "Timaukel": "Magallanes", "Natales": "Magallanes", "Torres del Paine": "Magallanes",
    "Santiago": "Metropolitana", "Cerrillos": "Metropolitana", "Cerro Navia": "Metropolitana", "Conchalí": "Metropolitana", "El Bosque": "Metropolitana", "Estación Central": "Metropolitana", "Huechuraba": "Metropolitana", "Independencia": "Metropolitana", "La Cisterna": "Metropolitana", "La Florida": "Metropolitana", "La Granja": "Metropolitana", "La Pintana": "Metropolitana", "La Reina": "Metropolitana", "Las Condes": "Metropolitana", "Lo Barnechea": "Metropolitana", "Lo Espejo": "Metropolitana", "Lo Prado": "Metropolitana", "Macul": "Metropolitana", "Maipú": "Metropolitana", "Ñuñoa": "Metropolitana", "Pedro Aguirre Cerda": "Metropolitana", "Peñalolén": "Metropolitana", "Providencia": "Metropolitana", "Pudahuel": "Metropolitana", "Quilicura": "Metropolitana", "Quinta Normal": "Metropolitana", "Recoleta": "Metropolitana", "Renca": "Metropolitana", "San Joaquín": "Metropolitana", "San Miguel": "Metropolitana", "San Ramón": "Metropolitana", "Vitacura": "Metropolitana", "Puente Alto": "Metropolitana", "Pirque": "Metropolitana", "San José de Maipo": "Metropolitana", "Colina": "Metropolitana", "Lampa": "Metropolitana", "Tiltil": "Metropolitana", "San Bernardo": "Metropolitana", "Buin": "Metropolitana", "Calera de Tango": "Metropolitana", "Paine": "Metropolitana", "Melipilla": "Metropolitana", "Alhué": "Metropolitana", "Curacaví": "Metropolitana", "María Pinto": "Metropolitana", "San Pedro": "Metropolitana", "Talagante": "Metropolitana", "El Monte": "Metropolitana", "Isla de Maipo": "Metropolitana", "Padre Hurtado": "Metropolitana", "Peñaflor": "Metropolitana"
};
